In [41]:
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.datasets import make_multilabel_classification
from sklearn.multiclass import OneVsRestClassifier
from sklearn.preprocessing import MultiLabelBinarizer

In [32]:
X, y = make_multilabel_classification(n_samples=100, n_features=10,
                                      n_classes=3, n_labels=3, random_state=42)
mlb = MultiLabelBinarizer(classes=[0,1,2])
y_bin = mlb.fit_transform(y)

In [33]:
X[0]

array([ 7.,  8.,  3.,  9.,  2.,  6.,  2., 12.,  8.,  4.])

In [34]:
y[0]

array([1, 1, 0])

In [35]:
y_bin[0]

array([1, 1, 0])

In [42]:
model1 = OneVsRestClassifier(SVC())
model1.fit(X, y)

OneVsRestClassifier(estimator=SVC())

In [43]:
model2 = OneVsRestClassifier(DecisionTreeClassifier())
model2.fit(X, y)

OneVsRestClassifier(estimator=DecisionTreeClassifier())

In [44]:
preds1 = model1.predict(X)

In [45]:
preds1[0]

array([1, 1, 0])

In [46]:
preds2 = model2.predict(X)

In [47]:
preds2[0]

array([1, 1, 0])

In [48]:
labels1 = mlb.inverse_transform(preds1)
labels2 = mlb.inverse_transform(preds2)

In [50]:
print(labels1[0])
print(labels2[0])

(np.int64(0), np.int64(1))
(np.int64(0), np.int64(1))
