# NumPy Fundumentals for Machine Learning

In [ ]:
import numpy as np

In [ ]:
np.random.seed(42)

## 1- NumPy Arrays

In [ ]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(a)

[1 2 3 4 5 6 7 8 9]


In [ ]:
type(a)

numpy.ndarray

In [ ]:
b = np.array([[1, 2.2, 3], [4, 5, 6], [7, 8, 9]])
print(b)

[[1.  2.2 3. ]
 [4.  5.  6. ]
 [7.  8.  9. ]]


## 2- ndarray Attributes

In [ ]:
a.shape

(9,)

In [ ]:
b.shape

(3, 3)

In [ ]:
b.dtype

dtype('float64')

In [ ]:
b_2 = b.astype('float32')
b_2.dtype

dtype('float32')

In [ ]:
a.dtype

dtype('int64')

In [ ]:
a_2 = a.astype(np.int8)
a_2.dtype

dtype('int8')

In [ ]:
b.ndim

2

In [ ]:
len(b.shape)

2

## 3- ndarray Creation Functions

In [ ]:
lin_arr = np.linspace(0, 10, 5)
lin_arr

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [ ]:
arr_arr = np.arange(0, 10, 2)
arr_arr

array([0, 2, 4, 6, 8])

In [ ]:
zeros_arr = np.zeros((3, 4))
zeros_arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
ones_arr = np.ones((3, 4))
ones_arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

## 4- Reshaping ndarrays

In [ ]:
reshaped_b = b.reshape((1, 9))
reshaped_b

array([[1. , 2.2, 3. , 4. , 5. , 6. , 7. , 8. , 9. ]])

In [ ]:
reshaped_b.shape

(1, 9)

In [ ]:
reshaped_b.reshape((9, 1))

array([[1. ],
       [2.2],
       [3. ],
       [4. ],
       [5. ],
       [6. ],
       [7. ],
       [8. ],
       [9. ]])

- `reshape((n, -1))`: Reshapes the array into `n` rows, with the number of columns automatically determined.
- `reshape((-1, n))`: Reshapes the array into `n` columns, with the number of rows automatically determined.

In [ ]:
reshaped_b.reshape((-1, 1))

array([[1. ],
       [2.2],
       [3. ],
       [4. ],
       [5. ],
       [6. ],
       [7. ],
       [8. ],
       [9. ]])

In [ ]:
reshaped_b.reshape((1, -1))

array([[1. , 2.2, 3. , 4. , 5. , 6. , 7. , 8. , 9. ]])

In [ ]:
b.reshape((3, 3, 1))

array([[[1. ],
        [2.2],
        [3. ]],

       [[4. ],
        [5. ],
        [6. ]],

       [[7. ],
        [8. ],
        [9. ]]])

## 5- Indexing and Slicing

In [ ]:
data = np.arange(1, 26).reshape((5, 5))
data

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
# Select first 3 rows
data[:3, :]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [ ]:
# Select first 3 rows and last 2 columns
data[:3, -2:]

array([[ 4,  5],
       [ 9, 10],
       [14, 15]])

In [ ]:
# Select 1st and 5th columns
data[:, [0, 4]]

array([[ 1,  5],
       [ 6, 10],
       [11, 15],
       [16, 20],
       [21, 25]])

In [ ]:
# Select elements >15
data[data > 15]

array([16, 17, 18, 19, 20, 21, 22, 23, 24, 25])

In [ ]:
# Select elements >5 and <15
data[(data > 5) & (data < 15)]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
np.sum(b)

np.float64(45.2)

In [ ]:
b

array([[1. , 2.2, 3. ],
       [4. , 5. , 6. ],
       [7. , 8. , 9. ]])

## 6- axis
- Axis 0:
In a 2D array, axis 0 represents the rows (vertical direction). In a 3D array, it represents the "depth" or the outermost dimension.

- Axis 1:
In a 2D array, axis 1 represents the columns (horizontal direction). In a 3D array, it represents the rows within each "depth slice."

- Axis 2 (and higher):
In a 3D array, axis 2 represents the columns within each "depth slice."

- For higher-dimensional arrays, the pattern continues, with each subsequent axis representing a deeper level of nesting.

In [ ]:
# sum of each column
np.sum(b, axis=0)

array([12. , 15.2, 18. ])

In [ ]:
# sum of each row
np.sum(b, axis=1)

array([ 6.2, 15. , 24. ])

## 7- ndarray Concatenation and Stacking

In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr3 = np.array([7, 8, 9])

np.concatenate((arr1, arr2, arr3))

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
mat1 = np.array([[1, 2, 3], [4, 5, 6]])
mat2 = np.array([[7, 8, 9], [10, 11, 12]])

np.concatenate((mat1, mat2), axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
np.concatenate((mat1, mat2), axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [ ]:
np.c_[mat1, mat2]

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [ ]:
np.stack((mat1, mat2), axis=1)

array([[[ 1,  2,  3],
        [ 7,  8,  9]],

       [[ 4,  5,  6],
        [10, 11, 12]]])

## 8- Statistical Operations

In [ ]:
data = np.arange(1, 26).reshape((5, 5))

In [ ]:
data

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
np.mean(data, axis=0)

array([ 3.,  8., 13., 18., 23.])

In [ ]:
np.argmax(data, axis=0)

array([4, 4, 4, 4, 4])

## 9- Random ndarray Generation

In [ ]:
np.random.randn(2, 3)

array([[-1.45818612,  0.54824567,  0.78507432],
       [-0.96882652,  0.00223083,  1.38750277]])

In [ ]:
np.random.normal(loc=5, scale=2, size=(3, 4))

array([[ 3.43190552, 11.14535648,  2.58589045,  6.2944258 ],
       [ 4.14073828,  0.47264536,  3.87427743, 11.03084978],
       [ 6.25075639,  5.85147294,  3.70546853,  4.95566772]])

## 9- Shuffling and Permutation

In [ ]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.random.shuffle(x)

In [ ]:
x

array([3, 7, 4, 8, 6, 5, 9, 2, 1])

In [ ]:
y = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
y_shuffled = np.random.permutation(y)

In [ ]:
y

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
y_shuffled

array([6, 1, 8, 5, 7, 9, 3, 4, 2])